[package]
name = "p-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
strum = { version = "0.27", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
